import { COLORS } from '~/lib/constants/colors';

export const BORDERS = {
  FOCUS_STATE: '1px dotted #666',
  SOLID_BLACK_1PX: `1px solid ${COLORS.GLOBAL.BLACK}`,
  SOLID_GRAY_10_1PX: `1px solid ${COLORS.LIGHT.GRAY_10}`,
  SOLID_GRAY_20_1PX: `1px solid ${COLORS.LIGHT.GRAY_20}`,
  SOLID_GRAY_20_2PX: `2px solid ${COLORS.LIGHT.GRAY_20}`,
  SOLID_GRAY_80_1PX: `1px solid ${COLORS.DARK.GRAY_80}`,
  SOLID_GRAY_90_1PX: `1px solid ${COLORS.DARK.GRAY_95}`,
  SOLID_GRAY_LIGHT_1PX: `1px solid ${COLORS.LIGHT.GRAY_LIGHT_SOLID}`,
  SOLID_ORANGE_1PX: `1px solid ${COLORS.GLOBAL.ORANGE}`,
  SOLID_ORANGE_2PX: `2px solid ${COLORS.GLOBAL.ORANGE}`,
  SOLID_ORANGE_SHADE_15_1PX: `1px solid ${COLORS.ORANGE.SHADE_15}`,
  SOLID_ORANGE_TINT_30_2PX: `2px solid ${COLORS.ORANGE.TINT_30_SOLID}`,
  SOLID_TRANSPARENT_1PX: '1px solid transparent',
  SOLID_TRANSPARENT_2PX: '2px solid transparent',
};
