const PREFIX = 'ST_';

export enum PROPERTIES {
  ADVANCED_VIEW = 'ADVANCED_VIEW',
  SESSION = 'SESSION',
  VEHICLE_METADATA = 'VEHICLE_METADATA',
}

export const LOCAL_STORAGE: Record<PROPERTIES, string> = {
  [PROPERTIES.ADVANCED_VIEW]: PREFIX + PROPERTIES.ADVANCED_VIEW,
  [PROPERTIES.SESSION]: PREFIX + 'SESSION',
  [PROPERTIES.VEHICLE_METADATA]: PREFIX + 'VEHICLE_METADATA',
};
