// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'

export type Icon =
  | 'account'
  | 'all-season'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'best-price'
  | 'checkmark'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'clear-input'
  | 'close'
  | 'customer-support'
  | 'economy'
  | 'facebook'
  | 'fire'
  | 'five-stars'
  | 'free-returns'
  | 'free-shipping'
  | 'geolocation'
  | 'grip'
  | 'instagram'
  | 'linkedin'
  | 'local-business'
  | 'location'
  | 'mail'
  | 'main-search'
  | 'menu'
  | 'money-back'
  | 'performance'
  | 'phone'
  | 'quantity-selector-car'
  | 'reviews-verified'
  | 'search'
  | 'shield'
  | 'small-chevron-down'
  | 'small-chevron-up'
  | 'smiley'
  | 'smiley-concerned'
  | 'smiley-wink'
  | 'star'
  | 'tire'
  | 'trending'
  | 'twitter'
  | 'vehicle-commercial'
  | 'vehicle-farm'
  | 'vehicle-industrial'
  | 'vehicle-light-truck'
  | 'vehicle-passenger'
  | 'vehicle-rv'
  | 'wheel'
  | 'winter'
  | 'youtube';

export type IconSize = { h: number; w: number };

// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'
