// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'

export type Icon =
  | 'account'
  | 'all-season'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'best-price'
  | 'brands-circular'
  | 'calendar'
  | 'calendar-big'
  | 'camera'
  | 'checkmark'
  | 'checkmark-big'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-small-down'
  | 'chevron-small-up'
  | 'chevron-up'
  | 'clear-input'
  | 'close'
  | 'customer-support'
  | 'drop-off-big'
  | 'external-link'
  | 'facebook'
  | 'find-tires-big'
  | 'fire'
  | 'five-stars'
  | 'forbidden'
  | 'free-returns'
  | 'free-shipping'
  | 'fuel-economy'
  | 'fuel-economy-big'
  | 'geolocation'
  | 'gift'
  | 'grip'
  | 'info'
  | 'instagram'
  | 'keys'
  | 'lightning-outline'
  | 'lightning-small'
  | 'linkedin'
  | 'local-business'
  | 'location'
  | 'mail'
  | 'main-search'
  | 'menu'
  | 'money-back'
  | 'notification'
  | 'performance'
  | 'phone'
  | 'pintrest'
  | 'play'
  | 'pro-tip-small'
  | 'quantity-selector-car'
  | 'quantity-selector-car-tilted'
  | 'rebate'
  | 'rebate-small'
  | 'returns-big'
  | 'review-verified'
  | 'run-flat'
  | 'run-flat-big'
  | 'search'
  | 'shipping-truck'
  | 'shipping-truck-outline'
  | 'shops-big'
  | 'smiley'
  | 'smiley-concerned'
  | 'smiley-wink'
  | 'star'
  | 'star-outline'
  | 'tag'
  | 'tag-small'
  | 'thumbs-up'
  | 'tip-mechanic'
  | 'tire'
  | 'tire-types-search'
  | 'tiretype-all-terrain'
  | 'tiretype-all-weather'
  | 'tiretype-antique'
  | 'tiretype-autocross'
  | 'tiretype-commercial'
  | 'tiretype-drag-racing'
  | 'tiretype-highway'
  | 'tiretype-mud'
  | 'tiretype-mud-terrain'
  | 'tiretype-performance'
  | 'tiretype-racing'
  | 'tiretype-sand-trail'
  | 'tiretype-sport'
  | 'tiretype-summer'
  | 'tiretype-touring'
  | 'tiretype-track-competition'
  | 'tiretype-uhp'
  | 'tiretype-winter'
  | 'trending'
  | 'twitter'
  | 'unknown'
  | 'vehicle-cart'
  | 'vehicle-commercial'
  | 'vehicle-farm'
  | 'vehicle-heavy-truck'
  | 'vehicle-industrial'
  | 'vehicle-light-truck'
  | 'vehicle-passenger'
  | 'vehicle-rv'
  | 'verified-small'
  | 'warranty'
  | 'warranty-small'
  | 'wheel'
  | 'wrench'
  | 'youtube';

export type IconType = 'COMMON' | 'OTHER';

export type IconObject = { h: number; type: IconType; w: number };

// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'
