// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'

import { Icon, IconObject } from './Icon.types';

export const ICONS: Record<string, Icon> = {
  ACCOUNT: 'account',
  ALL_SEASON: 'all-season',
  ARROW_DOWN: 'arrow-down',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  ARROW_UP: 'arrow-up',
  BELL: 'bell',
  BEST_PRICE: 'best-price',
  BRANDS_CIRCULAR: 'brands-circular',
  CALENDAR: 'calendar',
  CALENDAR_BIG: 'calendar-big',
  CAMERA: 'camera',
  CHECKMARK: 'checkmark',
  CHECKMARK_BIG: 'checkmark-big',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  CHEVRON_SMALL_DOWN: 'chevron-small-down',
  CHEVRON_SMALL_UP: 'chevron-small-up',
  CHEVRON_UP: 'chevron-up',
  CLEAR_INPUT: 'clear-input',
  CLOSE: 'close',
  CUSTOMER_SUPPORT: 'customer-support',
  DROP_OFF_BIG: 'drop-off-big',
  EXTERNAL_LINK: 'external-link',
  FACEBOOK: 'facebook',
  FIND_TIRES_BIG: 'find-tires-big',
  FIRE: 'fire',
  FIVE_STARS: 'five-stars',
  FORBIDDEN: 'forbidden',
  FREE_RETURNS: 'free-returns',
  FREE_SHIPPING: 'free-shipping',
  FUEL_ECONOMY: 'fuel-economy',
  FUEL_ECONOMY_BIG: 'fuel-economy-big',
  GEOLOCATION: 'geolocation',
  GIFT: 'gift',
  GRIP: 'grip',
  INFO: 'info',
  INSTAGRAM: 'instagram',
  KEYS: 'keys',
  LIGHTNING_OUTLINE: 'lightning-outline',
  LIGHTNING_SMALL: 'lightning-small',
  LINKEDIN: 'linkedin',
  LOCAL_BUSINESS: 'local-business',
  LOCATION: 'location',
  MAIL: 'mail',
  MAIN_SEARCH: 'main-search',
  MENU: 'menu',
  MONEY_BACK: 'money-back',
  NOTIFICATION: 'notification',
  PERFORMANCE: 'performance',
  PHONE: 'phone',
  PINTREST: 'pintrest',
  PLAY: 'play',
  PRO_TIP_SMALL: 'pro-tip-small',
  QUANTITY_SELECTOR_CAR: 'quantity-selector-car',
  QUANTITY_SELECTOR_CAR_TILTED: 'quantity-selector-car-tilted',
  REBATE: 'rebate',
  REBATE_SMALL: 'rebate-small',
  RETURNS_BIG: 'returns-big',
  REVIEW_VERIFIED: 'review-verified',
  RUN_FLAT: 'run-flat',
  RUN_FLAT_BIG: 'run-flat-big',
  SEARCH: 'search',
  SHIPPING_TRUCK: 'shipping-truck',
  SHIPPING_TRUCK_OUTLINE: 'shipping-truck-outline',
  SHOPS_BIG: 'shops-big',
  SIDEWALL: 'sidewall',
  SMILEY: 'smiley',
  SMILEY_CONCERNED: 'smiley-concerned',
  SMILEY_WINK: 'smiley-wink',
  STAR: 'star',
  STAR_OUTLINE: 'star-outline',
  TAG: 'tag',
  TAG_SMALL: 'tag-small',
  THUMBS_UP: 'thumbs-up',
  TIP_MECHANIC: 'tip-mechanic',
  TIRE: 'tire',
  TIRE_TYPES_SEARCH: 'tire-types-search',
  TIRETYPE_ALL_TERRAIN: 'tiretype-all-terrain',
  TIRETYPE_ALL_WEATHER: 'tiretype-all-weather',
  TIRETYPE_ANTIQUE: 'tiretype-antique',
  TIRETYPE_AUTOCROSS: 'tiretype-autocross',
  TIRETYPE_COMMERCIAL: 'tiretype-commercial',
  TIRETYPE_DRAG_RACING: 'tiretype-drag-racing',
  TIRETYPE_HIGHWAY: 'tiretype-highway',
  TIRETYPE_MUD: 'tiretype-mud',
  TIRETYPE_MUD_TERRAIN: 'tiretype-mud-terrain',
  TIRETYPE_PERFORMANCE: 'tiretype-performance',
  TIRETYPE_RACING: 'tiretype-racing',
  TIRETYPE_SAND_TRAIL: 'tiretype-sand-trail',
  TIRETYPE_SPORT: 'tiretype-sport',
  TIRETYPE_SUMMER: 'tiretype-summer',
  TIRETYPE_TOURING: 'tiretype-touring',
  TIRETYPE_TRACK_COMPETITION: 'tiretype-track-competition',
  TIRETYPE_UHP: 'tiretype-uhp',
  TIRETYPE_WINTER: 'tiretype-winter',
  TRENDING: 'trending',
  TWITTER: 'twitter',
  UNKNOWN: 'unknown',
  VEHICLE_CART: 'vehicle-cart',
  VEHICLE_COMMERCIAL: 'vehicle-commercial',
  VEHICLE_FARM: 'vehicle-farm',
  VEHICLE_HEAVY_TRUCK: 'vehicle-heavy-truck',
  VEHICLE_INDUSTRIAL: 'vehicle-industrial',
  VEHICLE_LIGHT_TRUCK: 'vehicle-light-truck',
  VEHICLE_PASSENGER: 'vehicle-passenger',
  VEHICLE_RV: 'vehicle-rv',
  VERIFIED_SMALL: 'verified-small',
  WARRANTY: 'warranty',
  WARRANTY_SMALL: 'warranty-small',
  WHEEL: 'wheel',
  WRENCH: 'wrench',
  YOUTUBE: 'youtube',
};

export const ICON_SIZES: Record<string, IconObject> = {
  ACCOUNT: { h: 17, type: 'COMMON', w: 14 },
  ALL_SEASON: { h: 29, type: 'OTHER', w: 30 },
  ARROW_DOWN: { h: 14, type: 'COMMON', w: 12 },
  ARROW_LEFT: { h: 12, type: 'COMMON', w: 14 },
  ARROW_RIGHT: { h: 12, type: 'COMMON', w: 14 },
  ARROW_UP: { h: 14, type: 'COMMON', w: 12 },
  BELL: { h: 42, type: 'COMMON', w: 41 },
  BEST_PRICE: { h: 35, type: 'OTHER', w: 38 },
  BRANDS_CIRCULAR: { h: 79, type: 'OTHER', w: 262 },
  CALENDAR: { h: 17, type: 'OTHER', w: 16 },
  CALENDAR_BIG: { h: 17, type: 'OTHER', w: 16 },
  CAMERA: { h: 82.7, type: 'OTHER', w: 100 },
  CHECKMARK: { h: 12, type: 'COMMON', w: 15 },
  CHECKMARK_BIG: { h: 35, type: 'OTHER', w: 35 },
  CHEVRON_DOWN: { h: 7, type: 'COMMON', w: 12 },
  CHEVRON_LEFT: { h: 12, type: 'COMMON', w: 7 },
  CHEVRON_RIGHT: { h: 12, type: 'COMMON', w: 7 },
  CHEVRON_SMALL_DOWN: { h: 5, type: 'COMMON', w: 8 },
  CHEVRON_SMALL_UP: { h: 5, type: 'COMMON', w: 8 },
  CHEVRON_UP: { h: 7, type: 'COMMON', w: 12 },
  CLEAR_INPUT: { h: 16, type: 'COMMON', w: 16 },
  CLOSE: { h: 12, type: 'COMMON', w: 12 },
  CUSTOMER_SUPPORT: { h: 32, type: 'OTHER', w: 31 },
  DROP_OFF_BIG: { h: 29, type: 'OTHER', w: 40 },
  EXTERNAL_LINK: { h: 16, type: 'COMMON', w: 16 },
  FACEBOOK: { h: 18, type: 'OTHER', w: 9 },
  FIND_TIRES_BIG: { h: 37, type: 'OTHER', w: 21 },
  FIRE: { h: 30, type: 'OTHER', w: 23 },
  FIVE_STARS: { h: 20, type: 'COMMON', w: 122 },
  FORBIDDEN: { h: 25, type: 'OTHER', w: 24 },
  FREE_RETURNS: { h: 23, type: 'OTHER', w: 28 },
  FREE_SHIPPING: { h: 25, type: 'OTHER', w: 66 },
  FUEL_ECONOMY: { h: 19, type: 'OTHER', w: 19 },
  FUEL_ECONOMY_BIG: { h: 36, type: 'OTHER', w: 36 },
  GEOLOCATION: { h: 16, type: 'OTHER', w: 16 },
  GIFT: { h: 34, type: 'OTHER', w: 35 },
  GRIP: { h: 8, type: 'OTHER', w: 6 },
  INFO: { h: 15, type: 'OTHER', w: 15 },
  INSTAGRAM: { h: 18, type: 'OTHER', w: 18 },
  KEYS: { h: 24, type: 'OTHER', w: 24 },
  LIGHTNING_OUTLINE: { h: 35, type: 'OTHER', w: 29 },
  LIGHTNING_SMALL: { h: 12, type: 'OTHER', w: 8 },
  LINKEDIN: { h: 18, type: 'OTHER', w: 18 },
  LOCAL_BUSINESS: { h: 33, type: 'OTHER', w: 69 },
  LOCATION: { h: 20, type: 'COMMON', w: 16 },
  MAIL: { h: 14, type: 'OTHER', w: 18 },
  MAIN_SEARCH: { h: 20, type: 'COMMON', w: 20 },
  MENU: { h: 8, type: 'COMMON', w: 16 },
  MONEY_BACK: { h: 32, type: 'OTHER', w: 30 },
  NOTIFICATION: { h: 57.38, type: 'OTHER', w: 50.65 },
  PERFORMANCE: { h: 31, type: 'OTHER', w: 32 },
  PHONE: { h: 14, type: 'OTHER', w: 16 },
  PINTREST: { h: 17.4, type: 'OTHER', w: 13.42 },
  PLAY: { h: 43, type: 'OTHER', w: 31 },
  PRO_TIP_SMALL: { h: 28, type: 'OTHER', w: 32 },
  QUANTITY_SELECTOR_CAR: { h: 31, type: 'OTHER', w: 34 },
  QUANTITY_SELECTOR_CAR_TILTED: { h: 39, type: 'OTHER', w: 39 },
  REBATE: { h: 24, type: 'OTHER', w: 24 },
  REBATE_SMALL: { h: 10, type: 'OTHER', w: 11 },
  RETURNS_BIG: { h: 39, type: 'OTHER', w: 42 },
  REVIEW_VERIFIED: { h: 13, type: 'OTHER', w: 13 },
  RUN_FLAT: { h: 24, type: 'OTHER', w: 24 },
  RUN_FLAT_BIG: { h: 35, type: 'OTHER', w: 35 },
  SEARCH: { h: 17, type: 'OTHER', w: 17 },
  SHIPPING_TRUCK: { h: 11, type: 'OTHER', w: 15 },
  SHIPPING_TRUCK_OUTLINE: { h: 17, type: 'OTHER', w: 28 },
  SHOPS_BIG: { h: 32, type: 'OTHER', w: 50 },
  SIDEWALL: { h: 159, type: 'OTHER', w: 115 },
  SMILEY: { h: 29, type: 'OTHER', w: 33 },
  SMILEY_CONCERNED: { h: 37, type: 'OTHER', w: 35 },
  SMILEY_WINK: { h: 30, type: 'OTHER', w: 33 },
  STAR: { h: 56, type: 'OTHER', w: 61 },
  STAR_OUTLINE: { h: 24, type: 'OTHER', w: 24 },
  TAG: { h: 24, type: 'OTHER', w: 24 },
  TAG_SMALL: { h: 10, type: 'OTHER', w: 10 },
  THUMBS_UP: { h: 24, type: 'OTHER', w: 24 },
  TIP_MECHANIC: { h: 38, type: 'OTHER', w: 39 },
  TIRE: { h: 30, type: 'OTHER', w: 30 },
  TIRE_TYPES_SEARCH: { h: 40, type: 'OTHER', w: 131 },
  TIRETYPE_ALL_TERRAIN: { h: 30, type: 'OTHER', w: 32 },
  TIRETYPE_ALL_WEATHER: { h: 27.8, type: 'OTHER', w: 29.3 },
  TIRETYPE_ANTIQUE: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_AUTOCROSS: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_COMMERCIAL: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_DRAG_RACING: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_HIGHWAY: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_MUD: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_MUD_TERRAIN: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_PERFORMANCE: { h: 30, type: 'OTHER', w: 31 },
  TIRETYPE_RACING: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_SAND_TRAIL: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_SPORT: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_SUMMER: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_TOURING: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_TRACK_COMPETITION: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_UHP: { h: 30, type: 'OTHER', w: 30 },
  TIRETYPE_WINTER: { h: 30, type: 'OTHER', w: 30 },
  TRENDING: { h: 13, type: 'OTHER', w: 24 },
  TWITTER: { h: 18, type: 'OTHER', w: 21 },
  UNKNOWN: { h: 24, type: 'OTHER', w: 24 },
  VEHICLE_CART: { h: 18, type: 'OTHER', w: 42 },
  VEHICLE_COMMERCIAL: { h: 25, type: 'OTHER', w: 60 },
  VEHICLE_FARM: { h: 36, type: 'OTHER', w: 48 },
  VEHICLE_HEAVY_TRUCK: { h: 30.12, type: 'OTHER', w: 58.58 },
  VEHICLE_INDUSTRIAL: { h: 36, type: 'OTHER', w: 45 },
  VEHICLE_LIGHT_TRUCK: { h: 25, type: 'OTHER', w: 63 },
  VEHICLE_PASSENGER: { h: 20, type: 'OTHER', w: 62 },
  VEHICLE_RV: { h: 30, type: 'OTHER', w: 62 },
  VERIFIED_SMALL: { h: 12, type: 'COMMON', w: 12 },
  WARRANTY: { h: 18, type: 'OTHER', w: 18 },
  WARRANTY_SMALL: { h: 11, type: 'OTHER', w: 11 },
  WHEEL: { h: 30, type: 'OTHER', w: 30 },
  WRENCH: { h: 10, type: 'OTHER', w: 11 },
  YOUTUBE: { h: 16, type: 'OTHER', w: 22 },
};

export const ICON_TYPES = { COMMON: 'COMMON', OTHER: 'OTHER' };

export const PUBLIC_ICONS_PATH = '/static/assets/icons-others';

// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'
