// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'

import { Icon, IconSize } from './Icon.types';

export const ICONS: Record<string, Icon> = {
  ACCOUNT: 'account',
  ALL_SEASON: 'all-season',
  ARROW_DOWN: 'arrow-down',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  ARROW_UP: 'arrow-up',
  CHECKMARK: 'checkmark',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  CHEVRON_UP: 'chevron-up',
  CLEAR_INPUT: 'clear-input',
  CLOSE: 'close',
  FACEBOOK: 'facebook',
  FIRE: 'fire',
  FIVE_STARS: 'five-stars',
  GEOLOCATION: 'geolocation',
  ICON_WHEEL: 'icon-wheel',
  INSTAGRAM: 'instagram',
  LINKEDIN: 'linkedin',
  LOCATION: 'location',
  MAIL: 'mail',
  MAIN_SEARCH: 'main-search',
  MENU: 'menu',
  PERFORMANCE: 'performance',
  PHONE: 'phone',
  REVIEWS_VERIFIED: 'reviews-verified',
  SEARCH: 'search',
  SMALL_CHEVRON_DOWN: 'small-chevron-down',
  SMALL_CHEVRON_UP: 'small-chevron-up',
  SMILEY: 'smiley',
  TIRE: 'tire',
  TRENDING: 'trending',
  TWITTER: 'twitter',
  VEHICLE_COMMERCIAL: 'vehicle-commercial',
  VEHICLE_LIGHT_TRUCK: 'vehicle-light-truck',
  VEHICLE_PASSENGER: 'vehicle-passenger',
  VEHICLE_RV: 'vehicle-rv',
  WHEEL: 'wheel',
  WINTER: 'winter',
  YOUTUBE: 'youtube',
};

export const ICON_SIZES: Record<string, IconSize> = {
  ACCOUNT: { h: 17, w: 14 },
  ALL_SEASON: { h: 29, w: 30 },
  ARROW_DOWN: { h: 14, w: 12 },
  ARROW_LEFT: { h: 12, w: 14 },
  ARROW_RIGHT: { h: 12, w: 14 },
  ARROW_UP: { h: 14, w: 12 },
  CHECKMARK: { h: 12, w: 15 },
  CHEVRON_DOWN: { h: 7, w: 12 },
  CHEVRON_LEFT: { h: 12, w: 7 },
  CHEVRON_RIGHT: { h: 12, w: 7 },
  CHEVRON_UP: { h: 7, w: 12 },
  CLEAR_INPUT: { h: 16, w: 16 },
  CLOSE: { h: 12, w: 12 },
  FACEBOOK: { h: 18, w: 9 },
  FIRE: { h: 30, w: 23 },
  FIVE_STARS: { h: 20, w: 122 },
  GEOLOCATION: { h: 25, w: 25 },
  ICON_WHEEL: { h: 70, w: 70 },
  INSTAGRAM: { h: 18, w: 18 },
  LINKEDIN: { h: 18, w: 18 },
  LOCATION: { h: 20, w: 16 },
  MAIL: { h: 17, w: 18 },
  MAIN_SEARCH: { h: 20, w: 20 },
  MENU: { h: 8, w: 16 },
  PERFORMANCE: { h: 31, w: 32 },
  PHONE: { h: 14, w: 16 },
  REVIEWS_VERIFIED: { h: 13, w: 13 },
  SEARCH: { h: 17, w: 17 },
  SMALL_CHEVRON_DOWN: { h: 5, w: 8 },
  SMALL_CHEVRON_UP: { h: 5, w: 8 },
  SMILEY: { h: 29, w: 33 },
  TIRE: { h: 30, w: 30 },
  TRENDING: { h: 13, w: 24 },
  TWITTER: { h: 18, w: 21 },
  VEHICLE_COMMERCIAL: { h: 43, w: 56 },
  VEHICLE_LIGHT_TRUCK: { h: 36, w: 54 },
  VEHICLE_PASSENGER: { h: 25, w: 55 },
  VEHICLE_RV: { h: 34, w: 54 },
  WHEEL: { h: 30, w: 30 },
  WINTER: { h: 72, w: 64 },
  YOUTUBE: { h: 16, w: 22 },
};

// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'
