// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'

import { Icon, IconSize } from './Icon.types';

export const ICONS: Record<string, Icon> = {
  ACCOUNT: 'account',
  ALL_SEASON: 'all-season',
  ARROW_DOWN: 'arrow-down',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  ARROW_UP: 'arrow-up',
  BEST_PRICE: 'best-price',
  CHECKMARK: 'checkmark',
  CHEVRON_DOWN: 'chevron-down',
  CHEVRON_LEFT: 'chevron-left',
  CHEVRON_RIGHT: 'chevron-right',
  CHEVRON_UP: 'chevron-up',
  CLEAR_INPUT: 'clear-input',
  CLOSE: 'close',
  CUSTOMER_SUPPORT: 'customer-support',
  ECONOMY: 'economy',
  FACEBOOK: 'facebook',
  FIRE: 'fire',
  FIVE_STARS: 'five-stars',
  FREE_RETURNS: 'free-returns',
  FREE_SHIPPING: 'free-shipping',
  GEOLOCATION: 'geolocation',
  GRIP: 'grip',
  INSTAGRAM: 'instagram',
  LINKEDIN: 'linkedin',
  LOCAL_BUSINESS: 'local-business',
  LOCATION: 'location',
  MAIL: 'mail',
  MAIN_SEARCH: 'main-search',
  MENU: 'menu',
  MONEY_BACK: 'money-back',
  PERFORMANCE: 'performance',
  PHONE: 'phone',
  QUANTITY_SELECTOR_CAR: 'quantity-selector-car',
  REVIEWS_VERIFIED: 'reviews-verified',
  SEARCH: 'search',
  SHIELD: 'shield',
  SMALL_CHEVRON_DOWN: 'small-chevron-down',
  SMALL_CHEVRON_UP: 'small-chevron-up',
  SMILEY: 'smiley',
  SMILEY_CONCERNED: 'smiley-concerned',
  SMILEY_WINK: 'smiley-wink',
  STAR: 'star',
  TIRE: 'tire',
  TRENDING: 'trending',
  TWITTER: 'twitter',
  VEHICLE_COMMERCIAL: 'vehicle-commercial',
  VEHICLE_FARM: 'vehicle-farm',
  VEHICLE_INDUSTRIAL: 'vehicle-industrial',
  VEHICLE_LIGHT_TRUCK: 'vehicle-light-truck',
  VEHICLE_PASSENGER: 'vehicle-passenger',
  VEHICLE_RV: 'vehicle-rv',
  WHEEL: 'wheel',
  WINTER: 'winter',
  YOUTUBE: 'youtube',
};

export const ICON_SIZES: Record<string, IconSize> = {
  ACCOUNT: { h: 17, w: 14 },
  ALL_SEASON: { h: 29, w: 30 },
  ARROW_DOWN: { h: 14, w: 12 },
  ARROW_LEFT: { h: 12, w: 14 },
  ARROW_RIGHT: { h: 12, w: 14 },
  ARROW_UP: { h: 14, w: 12 },
  BEST_PRICE: { h: 35, w: 65 },
  CHECKMARK: { h: 12, w: 15 },
  CHEVRON_DOWN: { h: 7, w: 12 },
  CHEVRON_LEFT: { h: 12, w: 7 },
  CHEVRON_RIGHT: { h: 12, w: 7 },
  CHEVRON_UP: { h: 7, w: 12 },
  CLEAR_INPUT: { h: 16, w: 16 },
  CLOSE: { h: 12, w: 12 },
  CUSTOMER_SUPPORT: { h: 32, w: 31 },
  ECONOMY: { h: 63, w: 63 },
  FACEBOOK: { h: 18, w: 9 },
  FIRE: { h: 30, w: 23 },
  FIVE_STARS: { h: 20, w: 122 },
  FREE_RETURNS: { h: 23, w: 28 },
  FREE_SHIPPING: { h: 25, w: 80 },
  GEOLOCATION: { h: 25, w: 25 },
  GRIP: { h: 8, w: 6 },
  INSTAGRAM: { h: 18, w: 18 },
  LINKEDIN: { h: 18, w: 18 },
  LOCAL_BUSINESS: { h: 33, w: 69 },
  LOCATION: { h: 20, w: 16 },
  MAIL: { h: 17, w: 18 },
  MAIN_SEARCH: { h: 20, w: 20 },
  MENU: { h: 8, w: 16 },
  MONEY_BACK: { h: 32, w: 29 },
  PERFORMANCE: { h: 31, w: 32 },
  PHONE: { h: 14, w: 16 },
  QUANTITY_SELECTOR_CAR: { h: 31, w: 34 },
  REVIEWS_VERIFIED: { h: 13, w: 13 },
  SEARCH: { h: 17, w: 17 },
  SHIELD: { h: 49, w: 50 },
  SMALL_CHEVRON_DOWN: { h: 5, w: 8 },
  SMALL_CHEVRON_UP: { h: 5, w: 8 },
  SMILEY: { h: 29, w: 33 },
  SMILEY_CONCERNED: { h: 37, w: 35 },
  SMILEY_WINK: { h: 30, w: 33 },
  STAR: { h: 56, w: 61 },
  TIRE: { h: 30, w: 30 },
  TRENDING: { h: 13, w: 24 },
  TWITTER: { h: 18, w: 21 },
  VEHICLE_COMMERCIAL: { h: 25, w: 60 },
  VEHICLE_FARM: { h: 36, w: 48 },
  VEHICLE_INDUSTRIAL: { h: 36, w: 45 },
  VEHICLE_LIGHT_TRUCK: { h: 25, w: 63 },
  VEHICLE_PASSENGER: { h: 20, w: 62 },
  VEHICLE_RV: { h: 30, w: 62 },
  WHEEL: { h: 30, w: 30 },
  WINTER: { h: 72, w: 64 },
  YOUTUBE: { h: 16, w: 22 },
};

// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'
