export const mockTireRatings = [
  {
    id: '1',
    tire: 'Firestone KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '2',
    tire: 'FiresGoodyear SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '3',
    tire: 'Goodyear SDL-Sport',
    rating: 5,
    ratingsQuantity: 336,
  },
  {
    id: '4',
    tire: 'Pirelli AZ850',
    rating: 2.5,
    ratingsQuantity: 58,
  },
  {
    id: '5',
    tire: 'Michelin KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '6',
    tire: 'Continental SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '7',
    tire: 'Accelera ATR Sport',
    rating: 5,
    ratingsQuantity: 336,
  },
  {
    id: '8',
    tire: 'Firestone AZ850',
    rating: 5,
    ratingsQuantity: 58,
  },
  {
    id: '9',
    tire: 'Goodyear KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '10',
    tire: 'Nexen SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '11',
    tire: 'Firestone KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '12',
    tire: 'FiresGoodyear SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '13',
    tire: 'Goodyear SDL-Sport',
    rating: 5,
    ratingsQuantity: 336,
  },
  {
    id: '14',
    tire: 'Pirelli AZ850',
    rating: 2.5,
    ratingsQuantity: 58,
  },
  {
    id: '15',
    tire: 'Michelin KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '16',
    tire: 'Continental SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '17',
    tire: 'Accelera ATR Sport',
    rating: 5,
    ratingsQuantity: 336,
  },
  {
    id: '18',
    tire: 'Firestone AZ850',
    rating: 5,
    ratingsQuantity: 58,
  },
  {
    id: '19',
    tire: 'Goodyear KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '20',
    tire: 'Nexen SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '21',
    tire: 'Firestone KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '22',
    tire: 'FiresGoodyear SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '23',
    tire: 'Goodyear SDL-Sport',
    rating: 5,
    ratingsQuantity: 336,
  },
  {
    id: '24',
    tire: 'Pirelli AZ850',
    rating: 2.5,
    ratingsQuantity: 58,
  },
  {
    id: '25',
    tire: 'Michelin KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '26',
    tire: 'Continental SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
  {
    id: '27',
    tire: 'Accelera ATR Sport',
    rating: 5,
    ratingsQuantity: 336,
  },
  {
    id: '28',
    tire: 'Firestone AZ850',
    rating: 5,
    ratingsQuantity: 58,
  },
  {
    id: '29',
    tire: 'Goodyear KC2000',
    rating: 5,
    ratingsQuantity: 33,
  },
  {
    id: '30',
    tire: 'Nexen SDL-Sport',
    rating: 5,
    ratingsQuantity: 110,
  },
];
