// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'

export enum Cars {
  'car--atv-utv' = 'car--atv-utv',
  'car--audi-a6' = 'car--audi-a6',
  'car--chevrolet-camaro' = 'car--chevrolet-camaro',
  'car--chevrolet-corvette' = 'car--chevrolet-corvette',
  'car--chevrolet-silverado-1500' = 'car--chevrolet-silverado-1500',
  'car--chevrolet-tahoe' = 'car--chevrolet-tahoe',
  'car--commercial' = 'car--commercial',
  'car--commercial-van' = 'car--commercial-van',
  'car--convertible' = 'car--convertible',
  'car--coupe' = 'car--coupe',
  'car--crossover' = 'car--crossover',
  'car--dodge-challenger' = 'car--dodge-challenger',
  'car--dodge-charger' = 'car--dodge-charger',
  'car--electric' = 'car--electric',
  'car--farm' = 'car--farm',
  'car--ford-escape' = 'car--ford-escape',
  'car--ford-explorer' = 'car--ford-explorer',
  'car--ford-f-150' = 'car--ford-f-150',
  'car--ford-fusion' = 'car--ford-fusion',
  'car--ford-mustang' = 'car--ford-mustang',
  'car--gmc-sierra-1500' = 'car--gmc-sierra-1500',
  'car--hatchback' = 'car--hatchback',
  'car--honda-accord' = 'car--honda-accord',
  'car--honda-civic' = 'car--honda-civic',
  'car--honda-crv' = 'car--honda-crv',
  'car--hybrid' = 'car--hybrid',
  'car--industrial' = 'car--industrial',
  'car--jeep-grand-cherokee' = 'car--jeep-grand-cherokee',
  'car--jeep-wrangler' = 'car--jeep-wrangler',
  'car--lawn-and-garden' = 'car--lawn-and-garden',
  'car--luxury' = 'car--luxury',
  'car--minivan' = 'car--minivan',
  'car--motocycle' = 'car--motocycle',
  'car--nissan-altima' = 'car--nissan-altima',
  'car--offroad' = 'car--offroad',
  'car--otr' = 'car--otr',
  'car--racing' = 'car--racing',
  'car--ram-1500' = 'car--ram-1500',
  'car--rv' = 'car--rv',
  'car--sedan' = 'car--sedan',
  'car--sports-car' = 'car--sports-car',
  'car--suv' = 'car--suv',
  'car--toyota-4runner' = 'car--toyota-4runner',
  'car--toyota-camry' = 'car--toyota-camry',
  'car--toyota-corolla' = 'car--toyota-corolla',
  'car--toyota-tacoma' = 'car--toyota-tacoma',
  'car--toyota-tundra' = 'car--toyota-tundra',
  'car--trailer' = 'car--trailer',
  'car--truck' = 'car--truck',
  'car--wagon' = 'car--wagon',
}

// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add new icons place svg file in /src/assets/icons
// and run 'yarn run generate-svg-sprite'
