// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add a new car, add the car svg file in /src/assets/cars
// and run 'yarn run generate-cars-constants'

export enum Cars {
  'car--atv-utv' = 'car--atv-utv',
  'car--audi-a6' = 'car--audi-a6',
  'car--bmw-x5' = 'car--bmw-x5',
  'car--chevrolet-camaro' = 'car--chevrolet-camaro',
  'car--chevrolet-colorado' = 'car--chevrolet-colorado',
  'car--chevrolet-corvette' = 'car--chevrolet-corvette',
  'car--chevrolet-equinox' = 'car--chevrolet-equinox',
  'car--chevrolet-impala' = 'car--chevrolet-impala',
  'car--chevrolet-malibu' = 'car--chevrolet-malibu',
  'car--chevrolet-silverado-1500' = 'car--chevrolet-silverado-1500',
  'car--chevrolet-tahoe' = 'car--chevrolet-tahoe',
  'car--chrysler-300' = 'car--chrysler-300',
  'car--commercial' = 'car--commercial',
  'car--commercial-van' = 'car--commercial-van',
  'car--convertible' = 'car--convertible',
  'car--coupe' = 'car--coupe',
  'car--crossover' = 'car--crossover',
  'car--dodge-challenger' = 'car--dodge-challenger',
  'car--dodge-charger' = 'car--dodge-charger',
  'car--dodge-durango' = 'car--dodge-durango',
  'car--electric' = 'car--electric',
  'car--electric-vehicle' = 'car--electric-vehicle',
  'car--farm' = 'car--farm',
  'car--ford-edge' = 'car--ford-edge',
  'car--ford-escape' = 'car--ford-escape',
  'car--ford-expedition' = 'car--ford-expedition',
  'car--ford-explorer' = 'car--ford-explorer',
  'car--ford-f-150' = 'car--ford-f-150',
  'car--ford-f350-super-duty' = 'car--ford-f350-super-duty',
  'car--ford-focus' = 'car--ford-focus',
  'car--ford-fusion' = 'car--ford-fusion',
  'car--ford-mustang' = 'car--ford-mustang',
  'car--ford-ranger' = 'car--ford-ranger',
  'car--gmc-sierra-1500' = 'car--gmc-sierra-1500',
  'car--gmc-sierra-2500hd' = 'car--gmc-sierra-2500hd',
  'car--hatchback' = 'car--hatchback',
  'car--honda-accord' = 'car--honda-accord',
  'car--honda-civic' = 'car--honda-civic',
  'car--honda-crv' = 'car--honda-crv',
  'car--honda-odyssey' = 'car--honda-odyssey',
  'car--honda-pilot' = 'car--honda-pilot',
  'car--hybrid' = 'car--hybrid',
  'car--hyundai-sonata' = 'car--hyundai-sonata',
  'car--industrial' = 'car--industrial',
  'car--jeep-grand-cherokee' = 'car--jeep-grand-cherokee',
  'car--jeep-wrangler' = 'car--jeep-wrangler',
  'car--lawn-and-garden' = 'car--lawn-and-garden',
  'car--luxury' = 'car--luxury',
  'car--minivan' = 'car--minivan',
  'car--motocycle' = 'car--motocycle',
  'car--nissan-altima' = 'car--nissan-altima',
  'car--nissan-frontier' = 'car--nissan-frontier',
  'car--nissan-maxima' = 'car--nissan-maxima',
  'car--nissan-sentra' = 'car--nissan-sentra',
  'car--nissan-titan' = 'car--nissan-titan',
  'car--offroad' = 'car--offroad',
  'car--otr' = 'car--otr',
  'car--racing' = 'car--racing',
  'car--ram-1500' = 'car--ram-1500',
  'car--rv' = 'car--rv',
  'car--sedan' = 'car--sedan',
  'car--sports-car' = 'car--sports-car',
  'car--subaru-outback' = 'car--subaru-outback',
  'car--suv' = 'car--suv',
  'car--toyota-4runner' = 'car--toyota-4runner',
  'car--toyota-camry' = 'car--toyota-camry',
  'car--toyota-corolla' = 'car--toyota-corolla',
  'car--toyota-highlander' = 'car--toyota-highlander',
  'car--toyota-rav4' = 'car--toyota-rav4',
  'car--toyota-sienna' = 'car--toyota-sienna',
  'car--toyota-tacoma' = 'car--toyota-tacoma',
  'car--toyota-tundra' = 'car--toyota-tundra',
  'car--trailer' = 'car--trailer',
  'car--truck' = 'car--truck',
  'car--volkswagen-jetta' = 'car--volkswagen-jetta',
  'car--wagon' = 'car--wagon',
}

// DO NOT MANUALLY EDIT THIS FILE, this file is auto-generated.
// To add a new car, add the car svg file in /src/assets/cars
// and run 'yarn run generate-cars-constants'
