name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [dev, qa, master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run checks
      run: yarn checks
