name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [dev, qa, staging, master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run checks
      run: yarn checks
