name: Version QA

on:
  push:
    branches:
      - qa

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'qa'

    - name: Bump version and create tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        yarn version --minor
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'qa'
